### PR TITLE
feat(cli/src/WebhookHelpers, Webhook.node.ts): body response blank

### PR DESCRIPTION
**Pull request by jhaltercmu2020**
give the option to leave the response body as blank if option is selected.

### CODE REVIEW

**Comment by jhaltercmu2020** [comment]
@abourge Ready for review

https://trello.com/c/iS8I5cFW/539-dsbat-see-new-line-items-from-updates-while-retaining-customer-group-info-cached-in-the-console

**Review by abourge — APPROVED** [review]

**Comment by jhaltercmu2020** [comment]
@Ken-Michalak Ready for final review

https://trello.com/c/iS8I5cFW/539-dsbat-see-new-line-items-from-updates-while-retaining-customer-group-info-cached-in-the-console

**Review by Ken-Michalak — APPROVED** [review]

**Comment by Ken-Michalak** [comment]
@Jhalter5Stones Something in the build/test is failing. If you're going to make a pr to upstream that's going to have to be fixed.

**Comment by jhaltercmu2020** [comment]
@Ken-Michalak I cherry-picked just the 1 commit from this fork for my PR to upstream. I have already submitted it and it passed all checks:
https://github.com/n8n-io/n8n/pull/1806

**Pull request merged**
